version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch-browsers
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""      
    steps:
      - checkout
      - run: pip install --upgrade pip
      - run: pip freeze > requirements.txt
      - run: find -name "requirements.txt"
      - run: pip install -r requirements.txt