version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch-browsers
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
    steps:
      - checkout


      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.141.59.jar -log testreports/selenium.log
          background: true
          
      - run: pip freeze > requirements.txt
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}      
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt      
            pip install --upgrade pip
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"        

services:
  selenium-hub:
    image: selenium/hub:3.8.1          # 3.7.1 works instead
    ports:
      - 14444:4444


  chrome:
    image: selenium/node-chrome:3.8.1
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
    volumes:
      - /dev/shm:/dev/shm
      
jobs:
  build:      
    steps:
      - checkout      
      - run:
          command: |
            . venv/bin/activate
            python StravaLogin.py test
      - store_artifacts:
          path: testreports/
          destination: tr1
      - store_test_results:
          path: testreports/          