jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch-browsers
    steps:
      - checkout
      - run: mkdir screenshots
      - run: sudo pip install selenium
      - run: sudo pip install requests
      - run:
          command: python StravaLogin.py
      - store_artifacts:
          path: ./screenshots
          destination: screenshots-file
