version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch-browsers
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
    steps:
      - checkout
      - run: pip freeze > requirements.txt
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}      
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt      
            pip install --upgrade pip
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"            