version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch-browsers
    steps:
      - checkout
      - run: pip install --upgrade pip
      - run: pip freeze > requirements.txt
      - run: pip install -r requirements/dev.txt